"""
Sandboxed Python executor for ad-hoc agent computations.
Runs agent-generated code in a restricted environment with
read-only access to pre-fetched data.
"""

import subprocess
import tempfile
import json
import os
from pathlib import Path

EXECUTION_TIMEOUT = 10  # seconds
MAX_OUTPUT_SIZE = 50000  # characters

# Whitelist of allowed imports
ALLOWED_IMPORTS = {
    "json", "math", "statistics", "datetime", "collections",
    "itertools", "functools", "decimal", "fractions", "re"
}

async def execute_analysis(
    code: str,
    data_context: dict,
    company_id: str
) -> dict:
    """
    Execute agent-generated Python code in a sandboxed subprocess
    with pre-fetched data injected as variables.
    
    Args:
        code: Python code string generated by the agent
        data_context: Dict of data to inject (e.g. transactions, summaries)
        company_id: For audit logging
    
    Returns:
        {"success": bool, "output": str, "error": str or None}
    """
    
    # 1. Validate the code — reject dangerous patterns
    validation = _validate_code(code)
    if not validation["safe"]:
        return {"success": False, "output": "", "error": validation["reason"]}
    
    # 2. Build the sandboxed script
    sandbox_script = _build_sandbox_script(code, data_context)
    
    # 3. Write to temp file and execute in subprocess
    try:
        with tempfile.NamedTemporaryFile(mode='w', suffix='.py', delete=False, encoding='utf-8') as f:
            f.write(sandbox_script)
            f.flush()
            
            result = subprocess.run(
                ["python", "-u", f.name], # Using python on Windows usually instead of python3
                capture_output=True,
                text=True,
                timeout=EXECUTION_TIMEOUT,
                env={
                    "PATH": os.environ.get("PATH", ""),
                    "PYTHONDONTWRITEBYTECODE": "1",
                }
            )
            
        output = result.stdout[:MAX_OUTPUT_SIZE]
        error = result.stderr[:MAX_OUTPUT_SIZE] if result.returncode != 0 else None
        
        # Log this audit
        import aiosqlite
        from backend.database import DB_PATH
        async with aiosqlite.connect(DB_PATH) as db:
            await db.execute(
                "INSERT INTO agent_audit_log (company_id, action_type, input_summary, output_summary, code_executed, execution_result) VALUES (?, ?, ?, ?, ?, ?)",
                (company_id, "code_execution", "Ad-hoc Python execution", output[:100], code, "success" if result.returncode == 0 else "error")
            )
            await db.commit()
            
        return {"success": result.returncode == 0, "output": output, "error": error}
        
    except subprocess.TimeoutExpired:
        return {"success": False, "output": "", "error": "Execution timed out (10s limit)"}
    except Exception as e:
        return {"success": False, "output": "", "error": str(e)}
    finally:
        # Clean up temp file
        try:
            os.unlink(f.name)
        except:
            pass

def _validate_code(code: str) -> dict:
    """
    Basic static analysis to reject dangerous code patterns.
    """
    dangerous_patterns = [
        "import os", "import sys", "import subprocess", "import shutil",
        "import socket", "import http", "import urllib", "import requests",
        "open(", "exec(", "eval(", "compile(", "__import__",
        "import pickle", "import shelve", "import sqlite3",
        "import asyncio",  # prevent event loop manipulation
        "globals()", "locals()", "dir()", "getattr", "setattr", "delattr",
        "breakpoint()",
    ]
    
    for pattern in dangerous_patterns:
        if pattern in code:
            return {"safe": False, "reason": f"Blocked pattern: {pattern}"}
    
    return {"safe": True, "reason": None}

def _build_sandbox_script(code: str, data_context: dict) -> str:
    """
    Wrap the agent's code with data injection and safe imports.
    """
    data_json = json.dumps(data_context)
    
    return f'''
import json, math, statistics, datetime, collections, itertools, decimal, re

# === INJECTED DATA (read-only) ===
_raw_data = """{data_json}"""
data = json.loads(_raw_data)

# Convenience accessors
transactions = data.get("transactions", [])
summary = data.get("summary", {{}})
company = data.get("company", {{}})

# === AGENT CODE BELOW ===
{code}
'''
